### ISSUE TITLE
depends on things (unparse) that don't work

### ISSUE THREAD

**Issue by gitcnd** [alvinwan/pymini#2]
I ran "pip install" as per your instructions.

I was not expecting it to install something that requires a newer version of python than the one I was using when I did the install.

```
[cnd@RoG: Err:1~/Downloads/mipyshell/lib-min]$ cat test.py 
print(0)
[cnd@RoG:~/Downloads/mipyshell/lib-min]$ python -V
Python 3.8.10
[cnd@RoG:~/Downloads/mipyshell/lib-min]$ pymini --keep-module-names --keep-global-variables --single-file test.py 
Traceback (most recent call last):
  File "/home/cnd/bin/pymini", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pymini/cli.py", line 22, in main
    cleaned, modules = minify(
  File "/usr/local/lib/python3.8/dist-packages/pymini/pymini.py", line 757, in minify
    cleaned = list(pipeline.transform(*trees))
  File "/usr/local/lib/python3.8/dist-packages/pymini/pymini.py", line 29, in transform
    trees = transformer.transform(*trees)
  File "/usr/local/lib/python3.8/dist-packages/pymini/pymini.py", line 484, in transform
    yield ast.unparse(tree)
AttributeError: module 'ast' has no attribute 'unparse'
[cnd@RoG: Err:1~/Downloads/mipyshell/lib-min]$ 
```

**Comment by alvinwan** [comment]
Ah, thank you for reporting! Fixed in pymini 0.1.2.

The repo had already moved to Python 3.9+, but PyPI was still serving the old 0.1.1 package metadata. I’ve now published 0.1.2, which correctly declares Python >=3.9, so pip should no longer install it on Python 3.8.
